travis:
  secure:
    BINSTAR_TOKEN: Kfq9CQ1TwMF5a+tsO9Bp0v/viFXbZjCDf2V2BzbbqQNWGVK1l2UeVQchISSOBrLkOko2GU16x6wQcWECFlQsIdzzaIa/wkLtFlsQZdkkGby8VNKanj+rqYFxteHZ5vncff1YTao/RUhX1kC/5ukoi08ZkZBxagFPMeLlBS/LvSu//dydueGCrVuj1noSEahylBrQP25bL/J7FDWp1wnagiIyPo5htrcIZsHlfiJurY/YKcxnG3mlGxZVc108x/INCpPCON8DZFlWXAbRJ3VT5PxpgNmp5KUM0IYBBNe55r9xHz9xUx7RpiDT/IEfKefDjwWUC0P8x5MewcNoWQ/l3EWRccmB30BKxtSVgmC7GIkT7iAWYYD0gq1UKnmhRvOgOStFmvanRtjw0Egq+OaH5QKZhd4rtGnKGqokPkZnu4IowNz3NZlInvTRfA/APud9L/o5bXk55o8LGI5YQ9XHPtUckK22R3IRzFobyRYmuOHRqSuw7V9NQQQrri7BGkKbnuAilvxUM3TUw07lZOdRYiMT5eRC/HkJd7NFpHErmpByQ3E01/wuK0osUsY8UGnMQub03o0SV1j3fUUVb4Uzt8Eo5cGYyE8fweXrnpkU1vIfv3vEnDelToRpyXwPpj88dJvINLTQlUNl1biXS1ZB33PPnqvhkh1fvinvE2V2CF8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
